Snippit/urls.py
from django.conf.urls import patterns, include, url;
from django.core.urlresolvers import reverse;
from django.http import HttpResponseRedirect;



from django.contrib import admin;
admin.autodiscover();



def snippitRedirect(request):
	return HttpResponseRedirect("/snippit/");



urlpatterns = patterns("",
	url(r"^admin/", include(admin.site.urls)),
	url(r"^snippit/", include("snippit.urls", namespace = "snippit")),
	url(r"^/?$", snippitRedirect)
);



import settings;
if (settings.DEBUG):
	urlpatterns += patterns("django.views.static", (r"media/(?P<path>.*)", "serve", {"document_root": settings.MEDIA_ROOT}), );

snippit/urls.py
from django.conf.urls import patterns, include, url;
from snippit import views;
from django.core.urlresolvers import reverse;
from django.http import HttpResponseRedirect;



def indexRedirect(request):
	return HttpResponseRedirect(reverse("snippit:index"));




urlpatterns = patterns("",
	url(r"^index/$", views.Index.as_view(), name = "index"),
	url(r"^login/$", views.Index.as_view(), name = "login"),
	url(r"^new-snippet/$", views.NewSnippet.as_view(), name = "new-snippet"),
	url(r"^view-snippet/(?P<snippetId>.+?)/$", views.ViewSnippet.as_view(), name = "view-snippet"),
	url(r"^view-snippet/$", views.ViewSnippet.as_view(), name = "view-snippet"),
	url(r"^/?$", indexRedirect)
);

snippit/models.py
from django.db import models;
from django.contrib.auth.models import User;
from django.core.urlresolvers import reverse;

import string;
import random;


class UUIDField(models.CharField):
	def __init__(self, *args, **kwargs):
		kwargs["max_length"] = kwargs.get("max_length", 8);
		kwargs["blank"] = True;
		super(UUIDField, self).__init__(*args, **kwargs);



	def pre_save(self, modelInstance, add):
		if (add):
			value = str("".join(random.choice(string.ascii_lowercase + string.ascii_uppercase + string.digits) for x in range(self.max_length)));
			setattr(modelInstance, self.attname, value);
			return value;
		else:
			return super(models.CharField, self).pre_save(modelInstance, add);





PLAIN_TEXT = "pt";
LUA = "lua";
CPP = "cpp";
JAVASCRIPT = "js";
COFFEESCRIPT = "coffee"

LANGUAGE_CHOICES = (
	(PLAIN_TEXT, "Plain Text"),
	(LUA, "Lua"),
	(CPP, "C++"),
	(JAVASCRIPT, "JavaScript"),
	(COFFEESCRIPT, "CoffeeScript")
);


class Snippet(models.Model):
	uuid = UUIDField(primary_key = True, db_index = True, editable = False, max_length = 8);
	user = models.ForeignKey(User, related_name = "snippets", db_index = True, null = True, blank = True);
	title = models.CharField(max_length = 255, db_index = True, blank = True);
	language = models.CharField(max_length = 6, choices = LANGUAGE_CHOICES, default = PLAIN_TEXT);
	date = models.DateTimeField(db_index = True, auto_now_add = True);
	content = models.TextField();



	def getTitle(self):
		return self.title if len(self.title) != 0 else "Untitled";


	def getUsername(self):
		return self.user.username if self.user is not None else "Anonymous";


	# @permalink
	def getAbsoluteUrl(self):
		return reverse("snippit:view-snippet", args = [self.uuid]);

	absoluteUrl = property(getAbsoluteUrl);



	def __unicode__(self):
		return str(self.uuid);

snippit/forms.py
from django import forms;
from django.contrib.auth.models import User;
from snippit.models import Snippet, LANGUAGE_CHOICES;



class SnippetForm(forms.ModelForm):
	title = forms.CharField(help_text = "Title", required = False);
	content = forms.CharField(help_text = "Content", widget = forms.Textarea());
	language = forms.ChoiceField(help_text = "Language", choices = LANGUAGE_CHOICES);



	class Meta:
		model = Snippet;
		fields = ["title", "content", "language"];

snippit/views.py
from django.shortcuts import render;
from django.views.generic.base import View;
from snippit.models import Snippet;
from snippit.forms import SnippetForm;
from django.core.urlresolvers import reverse;
from django.http import HttpResponseRedirect;



class Index(View):
	def get(self, request):
		context = { };
		context["snippetForm"] = SnippetForm();
		context["recentSnippets"] = Snippet.objects.order_by("date");

		return render(request, "snippit/index.html", context);



class NewSnippet(View):
	def post(self, request):
		snippetForm = SnippetForm(data = request.POST);
		snippet = snippetForm.save();
		return HttpResponseRedirect(snippet.absoluteUrl);



class ViewSnippet(View):
	def get(self, request, snippetId = ""):
		snippet = None;
		try:
			snippet = Snippet.objects.get(uuid = snippetId)
		except (Snippet.DoesNotExist):
			pass;

		context = { };
		context["snippet"] = snippet;
		return render(request, "snippit/view_snippet.html", context);

templates/snippit/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Snippet | {% block title %}Share code!{% endblock %}</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
	</head>
	<body>
		<header id="site-header">
			<div id="inner-header">
				<a href="{% url 'snippit:index' %}"><h1 id="header-title">Snippit!</h1></a>
				<nav>
					<a href="{% url 'snippit:login' %}">Login</a>
				</nav>
			</div>
		</header>
		<main id="content">
			{% block content %}
			{% endblock %}
		</main>
		{% block script %}
		{% endblock %}
	</body>
</html>

templates/snippit/index.html
{% extends "snippit/base.html" %}
{% block content %}
	<section id="index-about">
		<h1 id="index-about-title">Welcome to Snippit</h1>
		<section id="index-about-details">
			Snippit is a new way to share code
		</section>
	</section>
	<section id="index-content">
		<section id="new-snippet">
			<h2 id="new-snippet-title">New snippet</h2>
			<form method="post" action="{% url 'snippit:new-snippet' %}">
				{% csrf_token %}
				{% for field in snippetForm.visible_fields %}
					{{ field.help_text }}
					{% if field.errors %}{{ field.errors }}{% endif %}
					<br>
					{{ field }}<br>
				{% endfor %}
				<input type="submit" name="submit" value="Snip!"/>
			</form>
		</section>
		<aside id="snippet-list">
			<h2>Recent snippets</h2>
			{% for snippet in recentSnippets %}
				<article class="recent-snippet">
					<a href="{{ snippet.absoluteUrl }}">{{ snippet.getTitle }}
					by
					{{ snippet.getUsername }}</a>
					<br>
					<span>{{ snippet.date }}</span>
					<br>
					<span>{{ snippet.get_language_display }}</span>
				</article>
				<br><br>
			{% endfor %}
		</aside>
	</section>
{% endblock %}

templates/snippit/view_snippet.html
{% extends "snippit/base.html" %}
{% load static %}
{% block title %}{{ snippet.title }}{% endblock %}
{% block content %}
	{% if snippet %}
		<hgroup id="view-snippet-title-group">
			<h1 id="view-snippet-title">{{ snippet.getTitle }}</h1>
			<h3 id="view-snippet-user">by {{ snippet.getUsername }}</h3>
			<h5>written in {{ snippet.get_language_display }}</h5>
		</hgroup>
		<pre id="view-snippet-pre"><code id="view-snippet-code"
			data-should-highlight="{% if snippet.language == 'pt' %}false{% else %}true{% endif %}"
			data-language="{{ snippet.get_language_display }}">{{ snippet.content }}</code></pre>
	{% else %}
		<h1>Snippet not found</h1>
	{% endif %}
{% endblock %}
{% block script %}
	<script src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
	<script src="{% static 'js/syntax_highlighter.js' %}"></script>
{% endblock %}